name: Setup CI
description: Sets up Node.js and installs dependencies for CI workflows

runs:
  using: composite
  steps:
    - name: Install Node
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 20
        cache: "npm"

    - name: Install dependencies
      shell: bash
      run: npm ci
